runtime: go

# to allow for websockets to be used
env: flex
runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "1.21"

# to prevent moolah from going bye bye
instance_class: B1
manual_scaling:
  instances: 1

# for websockets to be useful
network:
  session_affinity: true

service_account: dwg-games@appspot.gserviceaccount.com
