package shape

const coordinateShape = "x:n y:n"
const costShape = "food:n wood:n stone:n gold:n"
const identityShape = "client_id:n ai_player_id:n player_id:n nickname:s connected:b"
const gameShape = "board_size:n population_limit:n turn_number:n giving_orders:b background_image:s background_top_left:a background_top_right:a game_base:o players:a spaces:a space_links:a regions:a"
const playerShape = "player:o population_limit:n max_population_limit:n score:n color:s orders_submitted:b eliminated:b buildings:a units:a active_orders:a researched_techs:o"
const privatePlayerShape = "resources:o turn_report:o? planned_foundations:a available_mercenaries:a auto_renewals:a"
const unexploredShape = "coordinate:o coordinate_key:n visibility:n"
const exploredShape = unexploredShape + " terrain_id:n terrain_type:n display_name:s gold_income:n ownership:n zones:a resources:a buildings:a"
const zoneShape = "coordinate:o coordinate_key:n terrain_override:n ownership:n"
const resourceShape = "internal_id:n resource_id:n display_name:s space_coordinate:o zone_coordinate:o resources_left:n base_gather_speed:n gather_capacity:n"
const unitShape = "internal_id:n player_id:n unit_id:n unit_type:n display_name:s space_coordinate:o zone_coordinate:o turn_stamina:n current_stamina:n max_stamina:n combat_stats:o attack_range:n active_orders:a builds:a"
const privateUnitShape = "stance:n interrupt_current:b attack_back:b target_priority:a"
const buildingShape = "internal_id:n player_id:n building_id:n display_name:s space_coordinate:o zone_coordinate:o population_support:n combat_stats:o under_construction:b stamina_remaining:n construction_stamina_total:n turn_stamina:n current_stamina:n max_stamina:n garrison_capacity:n attack_range:n has_garrisoned_units:b produces:a active_orders:a production_queue:a"
const privateBuildingShape = "garrisoned_units:a renewing:b auto_attack:b interrupt_current:b target_priority:a"
const farmShape = "resources_left:n resource_capacity:n renew_stamina:n gather_capacity:n base_gather_speed:n renew_cost:o resource_category:n"
const combatShape = "health:n max_health:n attack_type:n attack_blunt:n attack_piercing:n attack_magic:n defense_blunt:n defense_piercing:n defense_magic:n penetration_blunt:n penetration_piercing:n penetration_magic:n"
const orderShape = "internal_id:n player_id:n order_type:n target_id:n turn_received:n turn_resolved:n clear_previous_orders:b subjects:a"
const producibleShape = "row:n col:n kind:n id:n cost:o stamina_cost:n display_name:s description:s required_tech_id:n"
const garrisonUnitShape = "internal_id:n player_id:n unit_id:n unit_type:n display_name:s turn_stamina:n current_stamina:n max_stamina:n combat_stats:o attack_range:n active_orders:a builds:a garrisoned_in:n"
